### ISSUE TITLE
Extra code to disable a button

### ISSUE THREAD

**Issue by keithcha** [IBM/commerce-ui#11]
https://github.com/IBM/commerce-ui/blob/ccb1880a67bf42ac7835c4ed6ef1885cc0e674b2/commerce-admin-console/src/app/features/organizations/list-organizations/list-organizations.component.html#L14

According to https://www.carbondesignsystem.com/components/button/code, adding a disabled attribute is enough to disable a button

**Comment by alazgulec-ibm** [comment]
Then what's the problem here?
