### ISSUE TITLE
Test Case Development

### ISSUE THREAD

**Issue by sriniramas** [IBM/commerce-ui#27]
This issue (user story / story) is for the creation of Test Cases that include both Manual and Automation Test Cases. The following is the estimate:
1. Manual Test cases --> 30 hours
2. Automation test cases --> 60 hours
Automation test cases include the following activities:
a) Framework design
b) Script development

**Comment by sriniramas** [comment]
Assigning this issue to Narasimha Rao Nukala and Jagadeesh.

**Comment by sriniramas** [comment]
Closed the issue by mistake.

**Comment by IBMjack** [comment]
1. Prepared Functional flow doc for internal reference and shared for review.

**Comment by jackHcl** [comment]
1.Gone through the test scenarios and found , no access for me . Sent out a mail and awaiting for the access.
2. Preparing Test cases for the New Master Category Screen

**Comment by sriniramas** [comment]
Task is completed.
