### ISSUE TITLE
Create "Search Results" page/s

### ISSUE THREAD

**Issue by sriniramas** [IBM/commerce-ui#32]
Create "Search Results" page/s

**Comment by charankumaryadavg** [comment]
- I have committed search with dropdown and search component
- I am trying to create header but I have a blocker UI Shell
- I got a reply in slack I will do tomorrow
- I am currently exploring ngx-translate

**Comment by charankumaryadavg** [comment]
- Working on ngx-translate for search table and component  

- some UI issues are resolved in search component and implemented carbon icon and dropdown for table

**Comment by sriniramas** [comment]
Task is completed.
