### ISSUE TITLE
Clean up of Search Resutls web page/s

### ISSUE THREAD

**Issue by sriniramas** [IBM/commerce-ui#38]
To remove Bootstrap dependencies and any translation text that may be in the code.

**Comment by charankumaryadavg** [comment]
- worked on ngx-translate for search component and table with some css changes and committed

- started working on UI Shell for header

**Comment by charankumaryadavg** [comment]
- I have resolved  merge conflict issue.

- I have cloned and merged and committed the code again  because of some git pull issue

- working on UI Shell but its not coming properly and shared that screenshot in ng-carbon 
<img width="495" alt="screenshot 2019-02-05 at 6 21 37 pm" src="https://user-images.githubusercontent.com/46446908/52274699-76a4cb00-2973-11e9-8d7f-54fb50e45416.png">

**Comment by charankumaryadavg** [comment]
- working on header 

1. search and dropdown completed in header

2. working on Icons(@carbon/icons-angular) for header

**Comment by charankumaryadavg** [comment]
- worked on header

1. worked on dropdown : Issue is its accepting 3items to display for selection so i have increased the max-width of the menu

2. I have added Icons in the header but there is menu icon and IBM[platform] is there I cant able  to remove 

3.some icons don't have outline and some icons are not available

4. I have merged my header but its overcoming another header  so i will resolve tomorrow and then I I will commit it

**Comment by charankumaryadavg** [comment]
- working on header

1. I have set the display to be none to remove icons and IBM in the header

2. I have implemented Main header

3. All the headers(Main header,File menu header and Icon header) are occupying same place. I am working on this it will take some time to complete

**Comment by sriniramas** [comment]
This task/issue is completed.

**Comment by sriniramas** [comment]
Reopened the issue for Charan to put in the findings that he got from the Carbon team.

**Comment by charankumaryadavg** [comment]
Header

- Today I have tried with some changes in the header till evening but I cant able to resolve it, after that communicated with carbon team they told me that use custom toolbar instead of navbar for the Icon header so I should start from the scratch for the Icon header.

**Comment by charankumaryadavg** [comment]
Headers

- Started and completed Toolbar header

- Implemented Toolbar and Main header in the application

- some functionality is pending for Main header, I will complete and commit it Tomorrow

**Comment by charankumaryadavg** [comment]
Header

- Made some css changes in the headers and committed the code

- Tried to work on button menu but carbon doesn't have button menu so I have posted the message in the carbon-ng channel.

**Comment by charankumaryadavg** [comment]
header

- implemented menu for the header and done some css changes and committed it

**Comment by sriniramas** [comment]
Task is delivered and so being closed.
