### ISSUE TITLE
Clean up of Header and Footer code

### ISSUE THREAD

**Issue by sriniramas** [IBM/commerce-ui#40]
Remove Bootstrap dependencies and remove and translation text in the code.

**Comment by hclnaresh** [comment]
Removed Bootstrap and updated the hardcoded text with translatable internalization format. 

Updated the functionality of navbar- like disabling of the links on load of particular component.

**Comment by hclnaresh** [comment]
Working on footer component and modal component and implementing the carbon icons in these components

**Comment by hclnaresh** [comment]
Updated footer component and modal component with styling and carbon icons and specifying unique ids.
Removed unwanted links in sidebar component and styling.

**Comment by sriniramas** [comment]
This task/issue is now completed and so has been closed.
