### ISSUE TITLE
Manual Test cases to be created

### ISSUE THREAD

**Issue by sriniramas** [IBM/commerce-ui#42]
Create Manual Test Cases for the following screens/web pages:
1. Landing Page
2. Select Master Category
3. New Master Category
4. Search Results
5. Extended Sites Catalog Store

**Comment by jackHcl** [comment]
* Landing Page - Completed the test cases
* Select Master Category - Completed the test cases
* New Master Category - Completed the test cases

**Comment by jackHcl** [comment]
New Master Category :
 - Associated Assets = = Completed the test cases
-   Content = Completed the test cases
- References = Completed the test cases

**Comment by jackHcl** [comment]
Catalog Tool:

Search   Results = Completed the test cases
Unassigned   Catalog Entries = Completed the test cases
Extended   Sites Catalog Asset Store= Completed the test cases

**Comment by sriniramas** [comment]
This task/issue is completed.
