### ISSUE TITLE
Create Automation Test Cases for the Extended Sites Catalog Asset Store and Search Results web page/s

### ISSUE THREAD

**Issue by sriniramas** [IBM/commerce-ui#43]
Create Automation Test Cases for the Search Results web page/s

**Comment by narasimhanukala** [comment]
1. Checked out Existing Automation Framework from git Master repository (https://github.com/IBM/commerce-ui) and had a glance at the scripts.
2. Writing automation scripts for 'Extended Sites Catalog Asset Store' module.

**Comment by narasimhanukala** [comment]
Designed Automation Scripts for validating content and table structure on Extended Sites Catalog Asset Store page.

**Comment by narasimhanukala** [comment]
1. Resolved Dependency issues of the legacy Automation Framework of modules 'commerce-management-fixture' and 'orgadmin-fvt-tests'.
2. Prepared a Gradle build environment to demonstrate the automation scripts developed till date to team in todays weekly meeting call.

**Comment by narasimhanukala** [comment]
Modified the Scripts as per the Page Redesign.
Created classes for the pages of 10,11 and 13. test cases will be added once pages are delivered to QA

**Comment by narasimhanukala** [comment]
Automation Scripts till date are placed in Git in the branch 'HCL_Catalogs' of 'commerce-ui'

**Comment by narasimhanukala** [comment]
Created a custom script to select specific Store from Store dropdown based on Store Name.

**Comment by narasimhanukala** [comment]
Automation Scripts updated with Store Dropdown Selection and Search items. and Scripts are pushed to 'CatalogStore' branch of 'commerce-ui'

**Comment by narasimhanukala** [comment]
Updating automation scripts based on Store Selection..

**Comment by narasimhanukala** [comment]
Updated scripts for Catalog Upload page and commited into git branch 'CatalogStore'

**Comment by sriniramas** [comment]
Task is completed.
