### ISSUE TITLE
Develop trhe Catalog Uploads web page

### ISSUE THREAD

**Issue by sriniramas** [IBM/commerce-ui#65]
Tasks involved in the development of the new web page - Catalog Uploads

**Comment by charankumaryadavg** [comment]
- completed UI for catalog uploads and new catalog uploads and functionality is in progress

**Comment by charankumaryadavg** [comment]
Catalog Uploads
- added scroll, dropdowns and File uploader with .xml and .csv restriction

- calculated the size of the file

- save functionality is in progress

**Comment by charankumaryadavg** [comment]
Catalog Uploads

- done some css changes

-  save functionality is completed and committed the code

**Comment by sriniramas** [comment]
Task is closed as the deliverables are completed.
