### ISSUE TITLE
Error handler could've been abstracted out. 

### ISSUE THREAD

**Issue by keithcha** [IBM/commerce-ui#8]
https://github.com/IBM/commerce-ui/blob/ccb1880a67bf42ac7835c4ed6ef1885cc0e674b2/commerce-admin-console/src/app/features/organizations/organizations.main.service.ts#L111

Seems like the same code is run over and over again just with a different error

**Comment by alazgulec-ibm** [comment]
How would you suggest I do it Keith?

**Comment by keithcha** [comment]
Can this be pulled out into a service so we have one implementation across the whole app?
